version: "3.1"
services:
  stormy_files:
    image: jfloff/alpine-python:recent-onbuild
    command: bash -c "cd /files && python3 -m http.server 8081"
    volumes:
      - "./files:/files"
    ports:
      - "8081:8081"

